// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvjkuwssnyssoxtdovjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2amt1d3Nzbnlzc294dGRvdmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTI4NjksImV4cCI6MjA3Mjk4ODg2OX0.MqcowjSae2KLDWTiYknaQVX-PMucyAcfOHpl9B2CNEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});